Updated based on feedback
cloud-native-security-controls/controls-catalog pull request #18
Opened 2022-08-19 20:36 UTC by stenio123

Update based on https://github.com/cloud-native-security-controls/controls-catalog/issues/6

Detailed feedback response: https://drive.google.com/file/d/1zTmlpXZezjoQJrA7LzYIjO2yFen72SsJ/view?usp=sharing

2022-08-19 20:37 UTC, stenio123 commented
@JonZeolla JonZeolla

2022-08-26 23:54 UTC, JonZeolla commented
@pratiklotia do you have an idea of when you'll get a chance to look at this?

2022-08-30 17:03 UTC, JonZeolla requested changes
Feedback inline, otherwise looking great!  Didn't check that this properly renders as CSV afterward my suggested changes.

2022-08-30 17:03 UTC, JonZeolla commented on controls/controls_catalog_v1.0.csv
> +172,SSCP v1.0,Securing Deployments,Use a framework for managing software updates,"Use TUF to enforce the updating of software. The Update Framework (TUF) is a specification for delivering software up
There was some commentary on this item; changed this to 'consider' and accept the upstream feedback suggestion.
```suggestion
172,SSCP v1.0,Securing Deployments,Use an automated approach for managing software updates,"Consider using The Update Framework (TUF) to enforce the updating of software. TUF is a specification for delivering software updates in a secure, reliable and trusted way",,High,High
```

2022-08-30 17:03 UTC, JonZeolla commented on controls/controls_catalog_v1.0.csv
> +192,SSCP v1.0,Securing the Source Code,Use SSH keys to provide developers access to source code repositories,,AC-1 REMOTE ACCESS,Moderate to High,Moderate to High
The contradiction of 191 and 192 is great feedback for the upstream software supply chain white paper.

2022-08-30 17:03 UTC, JonZeolla commented
@stenio123 @pratiklotia FYI I did an initial review of this

2022-09-02 16:12 UTC, pratiklotia commented on controls/controls_catalog_v1.0.csv
> +5,CNSWP v1.0,Access,Credentials and keys protecting sensitive workloads (health/finance/etc) are generated and managed independent of a cloud service provider,KMS and HMS are common technologies to a
Looks like these typos existed even before @stenio123' PR. (My understanding is that this line has been copied as is). I'd leave it up to @stenio123 if he would like to address these changes or have it in a separate PR.

2022-09-02 16:15 UTC, pratiklotia commented on controls/controls_catalog_v1.0.csv
> +27,CNSWP v1.0,Compute,The hardware root of trust is based in a Trusted Platform Module (TPM) or virtual TPM (vTPM),"Ensure HW root of trust extends to the OS kernel, modules, system images, container
Up to @stenio123 to take this suggestion. (Pre-existing)

2022-09-02 16:19 UTC, pratiklotia commented on controls/controls_catalog_v1.0.csv
> +47,CNSWP v1.0,Compute,Native secret stores are not configured for base64 encoding or stored in clear-text in the key-value store by default,Encoding is not encryption,SC-12(3) Systems & Communication
@JonZeolla Wouldn't the line above be a sufficient pointer? I felt that that control is specifically written to address what not to use.

2022-09-02 16:25 UTC, pratiklotia commented on controls/controls_catalog_v1.0.csv
> +65,CNSWP v1.0,Develop,Integrate vulnerability and configuration scanning in either the IDE or at the CI system during pull request,,SA-11(1) DEVELOPER TESTING AND EVALUATION | STATIC CODE ANALYSIS,N/
Suggestion: `vulnerability and configuration scanning in different stages of development such as the IDE and at the CI system during pull request`
I felt like IDE and CI scanning are not necessarily complementary. Both can and should co-exist.

2022-09-02 16:51 UTC, pratiklotia commented on controls/controls_catalog_v1.0.csv
> +108,CNSWP v1.0,Distribute,HSMs or credential managers should be used for protecting credentials,,SC-12(3) SYSTEMS & COMMUNICATION PROTECTION,N/A,N/A
Wouldn't `credential managers` in the first line itself mean software based ones? Alternatively, `HSMs or software-based credential managers should be used for protecting credentials`

2022-09-02 17:01 UTC, pratiklotia requested changes
Added minor suggestions, rest of the changes look good to me.
I'm concerned why the `file changed` tab shows so many changes. Has the formatting of the doc changed? Ideally only the controls where you have made changes should have shown up there. Instead it shows almost lines being changed.

2022-09-02 17:53 UTC, JonZeolla commented
@pratiklotia yes I think it is because of formatting.  I did a fair amount of manual validation of the content

2022-09-02 17:54 UTC, JonZeolla commented on controls/controls_catalog_v1.0.csv
> +108,CNSWP v1.0,Distribute,HSMs or credential managers should be used for protecting credentials,,SC-12(3) SYSTEMS & COMMUNICATION PROTECTION,N/A,N/A
I'm good either way

2022-09-02 17:56 UTC, JonZeolla commented on controls/controls_catalog_v1.0.csv
> +47,CNSWP v1.0,Compute,Native secret stores are not configured for base64 encoding or stored in clear-text in the key-value store by default,Encoding is not encryption,SC-12(3) Systems & Communication
I was thinking algorithms, but also wouldn't reinvent the wheel.  Instead just point to other docs like what [OWASP has](https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html).

2022-09-02 17:58 UTC, JonZeolla commented on controls/controls_catalog_v1.0.csv
> +5,CNSWP v1.0,Access,Credentials and keys protecting sensitive workloads (health/finance/etc) are generated and managed independent of a cloud service provider,KMS and HMS are common technologies to a
There was feedback on this item in [here](https://drive.google.com/file/d/1zTmlpXZezjoQJrA7LzYIjO2yFen72SsJ/view) which talks about the customer managed recommendation

2022-10-04 18:07 UTC, JonZeolla commented
@stenio123 do you know when you'll have a chance to look at this again?  Thanks!

2022-10-18 17:56 UTC, JonZeolla commented
@stenio123 I'd love to get this merged, have you had a chance to look at the feedback?

2022-11-29 19:24 UTC, pratiklotia commented on controls/controls_catalog_v1.0.csv
> +65,CNSWP v1.0,Develop,Integrate vulnerability and configuration scanning in either the IDE or at the CI system during pull request,,SA-11(1) DEVELOPER TESTING AND EVALUATION | STATIC CODE ANALYSIS,N/
```suggestion
65,CNSWP v1.0,Develop,Integrate vulnerability and configuration scanning in both the IDE and at the CI system during pull request,,SA-11(1) DEVELOPER TESTING AND EVALUATION | STATIC CODE ANALYSIS,N/A,N/A

```

2022-11-29 19:57 UTC, JonZeolla approved these changes
LGTM

2022-11-29 19:57 UTC, merged